
[target.i686-unknown-linux-gnu]
linker = "i686-elf-ld"
ar = "i686-elf-ar"

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-elf-ld"
ar = "x686_64-elf-ar"

[build]
# rustflags = ["-C", "link-arg=-nostdlib", "-C", "link-arg=-static"]
rustflags = ["-C", "relocation-model=static"]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]


